module.exports = [
  {
    Title: 'Congee & Fried Dough Stick',
    Included: 'Porridge and fries',
    Description:
      'Congee and Fried Dough Stick is a classic Chinese breakfast dish.',
    Price: '1.99',
    Category: 'Breakfast',
    Cooking_Time: 10,
    Servings: 1,
    Calories: 1000,
    TopMeal: true,
    Image: '/images/1.png',
  },

  {
    Title: 'Spring rolls',
    Included: 'Fried food made with a thin wrapper and wrapped in a filling',
    Description:
      'With fresh vegetables wrapped in rice paper, these China spring rolls are a refreshing appetizer for an Asian-inspired meal.',
    Price: 2.99,
    Category: 'Breakfast',
    Cooking_Time: 10,
    Servings: 2,
    Calories: 153,
    TopMeal: false,
    Image: '/images/12.png',
  },

  {
    Title: 'Minced Pork Congee with Preserved Egg',
    Included: 'Pork, porridge and preserved eggs',
    Description: 'A perfect breakfast',
    Price: 5.99,
    Category: 'Breakfast',
    Cooking_Time: 10,
    Servings: 1,
    Calories: 1400,
    TopMeal: false,
    Image: '/images/13.png',
  },

  {
    Title: 'Steamed vermicelli roll',
    Included: 'Flour and mince',
    Description: 'A perfect breakfast.',
    Price: 1.99,
    Category: 'Breakfast',
    Cooking_Time: 10,
    Servings: 4,
    Calories: 648,
    TopMeal: false,
    Image: '/images/14.png',
  },

  {
    Title: 'Potato powder',
    Included: 'Vermicelli and potatoes',
    Description: 'A perfect lunch',
    Price: 10.99,
    Category: 'Lunch',
    Cooking_Time: 10,
    Servings: 1,
    Calories: 1650,
    TopMeal: true,
    Image: '/images/21.png',
  },

  {
    Title: 'Beef powder',
    Included: 'Beef and powder',
    Description: 'A perfect lunch',
    Price: 10.99,
    Category: 'Lunch',
    Cooking_Time: 10,
    Servings: 1,
    Calories: 1400,
    TopMeal: false,
    Image: '/images/24.png',
  },

  {
    Title: 'Signature dish',
    Included: 'Delicious',
    Description: 'A perfect dinner.',
    Price: 32.99,
    Category: 'Dinner',
    Cooking_Time: 10,
    Servings: 1,
    Calories: 2400,
    TopMeal: true,
    Image: '/images/31.png',
  },

  {
    Title: 'Beef potato flour',
    Included: 'Beef and potato flour',
    Description: 'A perfect dinner.',
    Price: 1.99,
    Category: 'Dinner',
    Cooking_Time: 10,
    Servings: 1,
    Calories: 1200,
    TopMeal: true,
    Image: '/images/32.png',
  },

  {
    Title: 'Grilled fish',
    Included: 'Fish',
    Category: 'Dinner',
    Description: 'A perfect dinner.',
    Price: 2.99,
    Cooking_Time: 10,
    Servings: 1,
    Calories: 1600,
    TopMeal: false,
    Image: '/images/33.png',
  },

  {
    Title: 'Stir-fry beef',
    Included: 'Beef',
    Description: 'A perfect dinner.',
    Price: 9.99,
    Category: 'Dinner',
    Cooking_Time: 10,
    Servings: 1,
    Calories: 1500,
    TopMeal: false,
    Image: '/images/34.png',
  },
]
